### ISSUE TITLE
Issue when editing a check in post

### ISSUE THREAD

**Issue by davidmead** [idno/Known#757] opened 2015-02-12 19:25 UTC
I created a check in post while at lunch. It found me right away on my phone.

![screen shot 2015-02-12 at 2 19 37 pm](https://cloud.githubusercontent.com/assets/1266930/6175205/b22de0de-b2c2-11e4-855a-2cad577de54a.png)

But when I went to edit it , to add some more details, on my laptop it changed the location in the edit screen.

![screen shot 2015-02-12 at 2 19 56 pm](https://cloud.githubusercontent.com/assets/1266930/6175226/cf66fee2-b2c2-11e4-9169-137c1a501f71.png)

Is there a way to turn off the "locate" when editing? In this case I have to enter the address or scoot around on the map to find the original place again everytime I want to edit a check in.

**Comment by mapkyca** [comment] 2015-02-15 18:52
*probably* shouldn't update geo on edit...

**Comment by markwaters** [comment] 2015-03-16 16:14
Duplicate of #534

**Closed** 2015-03-16 23:42 UTC
Labels: Bug
