### ISSUE TITLE
IndiePub syndicate-to-expanded property is blank on hosted Known

### ISSUE THREAD

**Issue by kylewm** [idno/Known#1352] opened 2016-03-08 21:16 UTC
## While trying to do this:

Fetch `?q=syndicate-to` from the micropub endpoint
## I encountered this error:

syndicate-to looks good, but syndicate-to-expanded is empty, which means Woodwind draws ugly syndication buttons for @kevinmarks:

```
{
    "syndicate-to": [
        "twitter::kevinmarks",
        "facebook::10154585682935425",
        "facebook::863215510399318",
        "facebook::688447421193285",
        "facebook::159878817395294",
        "facebook::36123201464"
    ],
    "syndicate-to-expanded": []
}
```
## Some other notes:

This only seems to affect hosted Known. Tested known.kevinmarks.com and kylewm.withknown.com. Briefly reading the code, I don't even really see how this result is possible as both `Syndication::getServiceAccountStrings` and `Syndication::getServiceAccountData` iterate over the same structure.

**Comment by benwerd** [comment] 2016-03-08 21:29
I'm guessing this might also affect Convoy users? It's because the account data isn't actually stored on the site, but is registered in the Convoy database / server.

**Comment by kylewm** [comment] 2016-03-08 21:31
good lord, you'd think I would have remembered that since I wrote that code in IndiePub. thanks Ben.

**Comment by benwerd** [comment] 2016-03-08 21:49
On my list for today is updating this mechanism (partially so I can get the latest code on withknown.com). Is there something I should be looking at here in the same swoop?

**Comment by kylewm** [comment] 2016-03-08 21:54
It'd be awesome if there were a way to request the syndication endpoints as JSON from `hub/user/syndication`. I don't think there's quite enough info in the HTML to reconstruct the structured data version of the endpoints.

https://github.com/idno/Known/blob/master/IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php#L19

**Comment by kevinmarks** [comment] 2016-03-08 23:32
did you and @aaronpk converge this? the wiki has multiple suggestions on
how to do this
http://indiewebcamp.com/Micropub-brainstorming#Discovering_Supported_Syndication_Targets

**Comment by kylewm** [comment] 2016-03-08 23:38
@kevinmarks nope, I'm just using what Known gives me which is the "syndicate-to-expanded" bit from that document.

**Comment by benwerd** [comment] 2016-03-10 05:52
Reproduced and confirmed that the data isn't trickling down from the hub (although locally-saved account data, like webhook data, is).

**Comment by kevinmarks** [comment] 2016-04-26 22:13
so, what can I do to mitigate this? anything? my woodwind buttons are still ugly

**Comment by kylewm** [comment] 2016-04-26 22:17
Nothing at the moment, sorry. I'm open to suggestions :/

**Comment by mapkyca** [comment] 2017-05-04 16:59
Still an issue?

**Comment by kevinmarks** [comment] 2017-05-05 14:05
Um, I need to get a running version of woodwind to test it on. Quill sees
them now

**Comment by mapkyca** [comment] 2018-02-10 08:40
Closing

**Closed by mapkyca** 2018-02-10 08:40 UTC
