### ISSUE TITLE
Twitter links embed in post = strange inconsistency

### ISSUE THREAD

**Issue by benborges** [idno/Known#1462] opened 2016-05-24 13:39 UTC
## While trying to do this:
Twitter links embed are supposed to be part of Known core since a while but
## I encountered this error:
When I add multiple or even 1 twitter link in a "new post" type article I get this : https://1-m.cc/2016/manif24mai-contre-la-loipeeters-et-son-monde-pour-une-distribution 

Now If I add multiple twitter links to a "status post" type I get this : https://1-m.cc/2016/gauvain_d_santostatus735047064732770305gauvain_d_santostatus735047468543582208gauvain_d_santostatus735056213508009984gauvain_d_santostatus735058839234588672gauvain_d_santostatus735062626619826177gauvain_d_santostatus7350

It's like half of the link embed fine but the first serie doesn't. I'm not sure How to track this "bug" and establish if this is coming from my site or if it's a reproductible bug.

**Comment by kylewm** [comment] 2016-05-24 18:13
Embeds are always added to the bottom of the post, and it looks to me like all the links in the top half are represented by embeds in the bottom half. So I don't think this behavior is new nor a bug.

It may be preferable to embed tweets "in line" like Medium/Tumblr/etc. do; but that'd need some discussion!

**Comment by benborges** [comment] 2016-05-25 12:41
Still very strange to show the link + the embedded item. Would make more sense to hide the link when the content can be embedded, I guess that's what you call "in line" embeds?

but I confirm your point : all twitter links are embedded in the post, it's just done at the end of the post and it show all the links. 

I still don't understand why single tweets URL don't get embedded on simple status post type : https://1-m.cc/2016/manif24mai-contre-la-loipeeters-et-son-monde-pour-une-distribution

any explanation ?

**Comment by kylewm** [comment] 2016-05-25 16:05
> I still don't understand why single tweets URL don't get embedded on simple status post type : https://1-m.cc/2016/manif24mai-contre-la-loipeeters-et-son-monde-pour-une-distribution

This is a Text post (i.e. an article with a title and body), rather than a Status post... This type of posts can embed HTML and stuff, so it doesn't mess too much with the markup you give it.

**Comment by benborges** [comment] 2016-05-27 14:49
Yes sorry, i got mixed up between my previous test and this one, it is indeed a text post...but why does twitter embed of a single link won't embed ?
![screenshot_61](https://cloud.githubusercontent.com/assets/10617712/15611491/d84e0840-242a-11e6-8faa-85c9411e6cbb.png)

**Comment by kylewm** [comment] 2016-05-28 14:57
Text posts (articles) don't do automatic embeds -- the idea is you are fully in control of the HTML, to lay it out how you want. So it would be wrong for Known to automatically stick a Twitter embed in there. If you want an inline embed in an article, you can always copy the code for it from twitter and paste that into your post.

Closing this one for now since I think Known is behaving as intended, but feel free to reopen if you disagre!

**Closed by kylewm** 2016-05-28 14:57 UTC
