### ISSUE TITLE
Page metadata turns user icon into preview image

### ISSUE THREAD

**Issue by benwerd** [idno/known#2230] opened 2018-10-12 16:42 UTC
A user's photo should never be the preview image of a content page. (It could reasonably be the preview image of a profile page.) The preview image function needs to be able to prevent this from happening.

**Comment by mapkyca** [comment] 2018-10-12 16:55
Example?

**Comment by mapkyca** [comment] 2018-10-13 09:56
<a href="https://github.com/idno/Known/issues/2230" class="u-in-reply-to"></a>This ticket needs a bit more information:

Are we talking about the feed page, or a specific entity type (e.g. blog)? Is it related to open graph and/or the new structured data format? Or both?

I'm assuming you're talking about longform posts which attempt to extract a preview from images within the text, and I suspect (although I've not looked at the code) will fall back to owner if not found.

Is this what you're talking about here?

**Comment by jgmac1106** [comment] 2018-10-14 22:41
Here is an example as it usually shows during syndication but also in readers:

https://quickthoughts.jgregorymcverry.com/2018/10/14/scott_gruber-not-using-word-self-dogfooding-anymore-personal

https://twitter.com/jgmac1106/status/1051600113771171842

I am way to ugly for people to look at,

 I tried status updates, reply posts, and articles.

All post types without am image show my avatar image. 

Articles with an image uploaded will take first image
Articles where I manually add an image and add u-photo property class="u-photo" show broken image
Articles where I manually add an image and ad u-featured work fine
If I upload an image and then click on source editor to add additional properties just does funky stuff, but that isn't for this issue.

**Comment by jgmac1106** [comment] 2018-10-14 22:46
This seems to be throwing the image: link rel="apple-touch-icon" and the OpenGraph: <meta property="og:image" content="https://quickthoughts.jgregorymcverry.com/file/6802fbcdd3fada8cb61ffb798978f72f/thumb.jpg" />

Is there anyway I can strip the OG stuff and just use the u-featured property?

**Comment by jgmac1106** [comment] 2018-10-15 00:38
Turning off the setting for "Avatar as icon" removes the image from OpenGraph.

**Comment by mapkyca** [comment] 2018-10-15 07:53
<a href="https://github.com/idno/Known/issues/2230#issuecomment-429669652" class="u-in-reply-to"></a>I'd argue that if this only shows when "Avatar as icon" is set, then this isn't a bug and things are behaving as expected...

**Comment by jgmac1106** [comment] 2018-10-15 10:56
I would agree and think one could close this issue, though I did notice
OpenGraph was once an Idno plugin but it looks like it went into Core as I
could not find it.

**Comment by jgmac1106** [comment] 2018-10-15 18:32
I looked at the source code of this post: http://quickthoughts.jgregorymcverry.com/2018/10/15/i-also-think-these-features-will-be and  the OpenGraph stuff is gone but the images for retina apple display still seem to be there.

(Originally published at: http://jgregorymcverry.com/7919-2/)

**Comment by mapkyca** [comment] 2018-10-17 09:31
<a href="https://github.com/idno/Known/issues/2230" class="u-in-reply-to"></a>Retina icons shouldn't be profile pics however, they're mainly for if you bookmark the page on your iThing so you get a Known icon rather than the default.

**Comment by jgmac1106** [comment] 2018-10-17 10:35
Seems to be displaying though when the avatar is off. Turning off the
avatar does remove OpenGraph.

**Comment by mapkyca** [comment] 2018-10-17 10:57
<a href="https://github.com/idno/Known/issues/2230" class="u-in-reply-to"></a>Yes, OG tags should always be present, that's normal.

However, on my site, when I disable "avatar as icon", the og:image flips from the profile icon to the default K icon.

**Comment by mapkyca** [comment] 2018-12-21 18:17
As mentioned in #2308, the OG should use the image of the main post image of blog style posts (which I believe already should happen as that's a getIcon() override. Can't recall if Photo also does this, but if not, it should.

**Comment by mapkyca** [comment] 2018-12-21 18:36
No worries dude, sorry for giving the impression I was being curt!

**Comment by ejheil** [comment] 2018-12-21 19:20
all good :)

**Comment by ejheil** [comment] 2018-12-21 23:59
Yeah, confirmed, the og:image is set to the post's image in a regular post, but to the profile icon in a photo post.

**Comment by mapkyca** [comment] 2019-08-25 09:51
On my site, for status posts if the profile pic as icon is set I get the user icon as expected, for image or text types (with an image), I'm getting those images as thumbnail.

This is what I'd expect.

**Closed by mapkyca** 2019-08-25 09:51 UTC
