### ISSUE TITLE
Known Hybrid / PWA app

### ISSUE THREAD

**Issue by its-pranjalpandey** [idno/known#2633] opened 2019-12-11 17:55 UTC
ref from #2619 #2625 #2618 

Steps 
1) Create hybrid, PWA application using angular and possibly ionic 4 
2) Use known API as data source
3) While building it try adding information to API docs

**Comment by lindner** [comment] 2020-03-02 01:32
dupe of #2625  ?

**Closed** 2021-04-29 05:54 UTC
