### ISSUE TITLE
Top bar is black while browsing in Internet Explorer 10/11

### ISSUE THREAD

**Issue by jirkadus** [idno/Known#752] opened 2015-02-04 19:42 UTC
Hi,
I just noticed, that while browsing web in MS Explorer, it ignores some formatting styles (round corners of boxes, round profile picture), but mainly the top bar's background is black, in Chrome it is white. I see the same black bar at any other website using Known.

![ie](https://cloud.githubusercontent.com/assets/3834816/6048241/d660e9e6-aca6-11e4-8833-d64583287c23.png)
![chrome](https://cloud.githubusercontent.com/assets/3834816/6048244/dae7dcf4-aca6-11e4-948e-8044d7cdded5.png)

Edit: I am not IE regular user, but now I found that in IE whole Known behaves really wild. The panel to add posts, status etc. is invisible in IE and there is much more problems. Is it just me who sees it?

**Comment by mapkyca** [comment] 2015-02-04 23:37
I think it is high time that IE was taken out into the woods and shot, it's corpse burnt, the ashes buried at a crossroads and the ground salted. 

Probably a CSS "quirk".

**Comment by benwerd** [comment] 2015-02-04 23:50
We're aware of this issue, but are holding off because the next major version of Known will include a Bootstrap upgrade. We'll test it again once that happens.

Of course, Microsoft are moving onto a new browser, and once that's generally available, we'll test that too.

**Comment by jirkadus** [comment] 2015-02-05 13:43
I see, I did expect, some difference between IE and Chrome, but was surprised that it is that bad.
Thanks anyway, I am glad it is on the road map to deal with it. You do great job!

**Comment by erinjo** [comment] 2015-02-05 17:38
Hi jirkadus, thanks for pointing this out. The black bar is a known issue in IE 9 and lower, but I am surprised you are seeing this in IE 10 & 11. We have not had this as an issue when testing in IE 10 and 11. For more information, could you share what operating system you're using IE 10 and 11 with? That might help us reproduce your problem.

**Comment by jirkadus** [comment] 2015-02-05 20:58
Sure, sorry for in indefinite feedback. I use IE10 on Widows 7 Enterprise and IE11 on Windows 8.1. Pro. Both Windo

![screenshot 2015-02-05 20 49 16](https://cloud.githubusercontent.com/assets/3834816/6069057/2d2894fe-ad79-11e4-9ef1-7d306972dc8e.png)
ws on latest updates.

I am adding as well screenshot of my website after login, to show other differences. I did not post it earlier, because I wanted to demonstrate it on webpage administrated by you, to avoid speculation that it was caused by me and possible mistake during installation and playing with it (Although I changed only two things in code - added radius to the post corners and changed transparency parameter) Screen shot is from W8.1 Pro, IE11 and Chrome is in version Version 40.0.2214.94 (64-bit).

**Comment by erinjo** [comment] 2015-02-05 21:00
Thanks for this!

**Comment by erinjo** [comment] 2015-02-09 01:29
Hi Jiri – I just wanted to give you a quick update here.  I haven’t been able to find any machines to test on that specifically mirror your setup with Windows 8.1 Pro / IE 11 (or Windows 7 Enterprise).  On regular Windows 8.1 – IE 11 (and Windows 7 – IE 10) things come out ok, like the attached screenshot.  Without knowing more, I think the issue might lie in the rendering engine the Microsoft makes available for Pro and Enterprise versions of Windows 8 and 7.  From what I’ve found, there’s an ‘IE Enterprise’ option in the Pro and Enterprise versions to set the IE rendering engine back to function more like IE 8. This is so that legacy enterprise applications still function. You may be running into this, and thus some CSS and Javascript will not behave normally. 

![screen shot 2015-02-05 at 1 02 50 pm](https://cloud.githubusercontent.com/assets/1192220/6099820/f518a770-afb7-11e4-8c76-8505bb73f77f.png)

**Comment by benwerd** [comment] 2016-01-29 07:12
Noting @erinjo's really awesome reply here, and closing the ticket.

**Closed by benwerd** 2016-01-29 07:12 UTC
