### ISSUE TITLE
Emojis do not work in posts

### ISSUE THREAD

**Issue by capjamesg** [idno/Known#3118] opened 2022-09-05 12:02 UTC
## While trying to do this:

I tried to create a post using the built-in post creation interface. My post featured an emoji. When I submitted the form to create my post, the new post was not created.

## I encountered this error:

There was no visual error to indicate the emoji was not an allowed character type or caused an error. The post I tried to create was not created.

## Some other notes:

Here is my Known version number:

```
version = '1.3.1'
build = 2020120201
```

I am using MySQL.

**Comment by lindner** [comment] 2022-09-23 01:20
This is probably caused by the character set used by mysql not supporting the version of unicode required for emojis.  I fixed it a way back, but can't remember the details, eek!

**Comment by lindner** [comment] 2022-09-23 01:28
ah, yes, it's utf8mb4 character set you want.

here's a description of the process of converting:

https://mathiasbynens.be/notes/mysql-utf8mb4

The code itself and sql in `warmup/schemas` should be updated.  However I think there was a plan to use a schema manager instead of the hand-rolled SQL...

**Comment by lindner** [comment] 2022-09-24 03:54
Duplicate of #2451

**Closed as completed by lindner** 2022-09-24 03:54 UTC
