### ISSUE TITLE
Event creation looks somewhat broken

### ISSUE THREAD

**Issue by nekr0z** [idno/Known#907] opened 2015-05-22 16:04 UTC
I have been trying to create an event on my Known site (hosted account, no idea what version is running there), but every time I try I get a white page with the following rather cryptic message (copied verbatim):

����n�0�_e�R8H��J(������d61��X��!<=c���T�Ef&�����zz�|���>��ݡ7H=��y�,�����5���Մ	�dpzD�4@���4H@�P��&���D��������l-�ˡVNN��\� U�gu�^i�T�G �f V-{T_cw�O��bW����oa�V[�E��s����`�`�Њ(s�9lu���vk���9H^�s� ���L_�V뺖x��S�A>��G��$D�V7G�8�5'��Q�	j ����n��&���'t����y~��|�U^��^`Z_�!1���"ٔ�A�#���:+K^�=�x�~��X�W$���+x��,QB,.A�7fi�ҿ�3��^Q�$K�{�<`��q�E���Ҵ\���\�/��!��⿗�5�`CL���YVC�:I��nʟ�#��

I don't speak the language this message is in (whatever that might be), and I'm not really sure how the message of the successful event creation should look like, but seeing as how no event is added to my page I guess something is wrong here.

**Comment by mapkyca** [comment] 2015-05-22 16:36
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/907" class="u-in-reply-to"></a>Anything in the logs?

Also, might be worth pasting headers on the requests (use chrome dev tools or firefox with firebug installed)

Basically looks like something is corrupting the character encoding. I had something similar happen with an audio post which caused problems with modsecurity.

**Comment by benwerd** [comment] 2015-05-22 16:37
We're aware of an issue on the hosted service this morning with exactly
this result. Looking into it as a priority.

On Friday, May 22, 2015, Marcus Povey <notifications@github.com> wrote:

> <https://github.com/idno/Known/issues/907>Anything in the logs?
>
> Also, might be worth pasting headers on the requests (use chrome dev tools
> or firefox with firebug installed)
>
> Basically looks like something is corrupting the character encoding. I had
> something similar happen with an audio post which caused problems with
> modsecurity.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/907#issuecomment-104707115>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by erinjo** [comment] 2015-05-23 00:36
Thanks for sharing this @nekr0z. We've reproduced the issue, and we're working on a fix.

**Comment by benwerd** [comment] 2015-05-23 00:44
@nekr0z I just pushed a fix. Let us know if it worked for you!

**Comment by nekr0z** [comment] 2015-05-23 10:25
Allright, I got it now: it seems to work as it is supposed to, but only as long as there is at least one ASCII character in the event name (the rest of the fields don't seem to matter). In case there are no ASCII characters in the event name (for example, the event is called "Ужин" - "Dinner" in Russian) the same (or sligtly different) cryptic message appears.

So this is i18n issue. Unicode.

**Comment by mapkyca** [comment] 2015-05-23 10:39
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/907#issuecomment-104879289" class="u-in-reply-to"></a>For the record, self hosted appears to be fine. So this may be a hosted issue...

**Comment by mapkyca** [comment] 2015-05-23 10:56
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/907" class="u-in-reply-to"></a>Interestingly there's nothing special about how titles are saved in events... I wonder if it occurs anywhere else...

**Comment by mapkyca** [comment] 2015-05-23 10:59
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/907" class="u-in-reply-to"></a>Not able to replicate on hosted with procedure described (posting entirely in Russian)

**Comment by nekr0z** [comment] 2015-05-23 11:10
I can no longer reproduce it either, although I could an hour ago. Fix took time to propagate?

**Comment by mapkyca** [comment] 2015-05-23 15:01
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/907#issuecomment-104882505" class="u-in-reply-to"></a>Very likely

**Closed** 2015-05-23 15:05 UTC
