### ISSUE TITLE
Can't get Known set up on shared hosting due to apache conf issues

### ISSUE THREAD

**Issue by ejheil** [idno/known#2275] opened 2018-11-20 03:30 UTC
## While trying to do this:

Set up known on shared hosting (dreamhost) in a subdirectory of my main site (mysite.com/known), using the current version from git master.

## I encountered this error:

> Rewriting appears to be disabled. Usually this means "AllowOverride None" is set in apache2.conf which prevents Known's .htaccess from doing its thing. We tried to fetch a URL that should redirect to default.js
> 
> You can usually fix this by setting AllowOverride All in your Apache configuration.

## Some other notes:

I have no access to Dreamhost's apache.conf, because, shared hosting.  Putting "AllowOverride All" in known's .htaccess, or in my webroot's .htaccess, results in a 500 error.

Give us some context: 

* It'd also be really handy if you could tell us the contents of your ```version.known``` file

version = "0.9.9-a"
build = 2018111201

* What database are you using? (e.g. mongo, mysql, 

mysql

* Any warnings or errors in your admin/diagnostics page?

* Bonus points - are you able to illustrate the issue with a unit test? If so, submit it as a pull request!

**Comment by mapkyca** [comment] 2018-11-20 06:58
Duplicate of #2238

**Closed by mapkyca** 2018-11-20 06:58 UTC
