### ISSUE TITLE
Update same site cross-linking

### ISSUE THREAD

**Issue by Phyks** [idno/known#882] opened 2015-05-06 20:53 UTC
Hi,

I just noticed that if I linked an article on my Known instance in another article on my Known instance, there is a pingback and I receive an email notification saying that someone (me in fact) linked to one of my articles.

In this particular case, it was even more particular as I linked to a "page" (from the page plugin).

I think that same site linking should be kept between articles, but there should not be pingbacks when linking to a page on the same instance and same profile, no? And if the profile used to post both of the posts is the same (or Known instance is single user), there should not be any email notification, no?
##

**Comment by kylewm** [comment] 2016-02-04 18:05
I think webmention between articles is a feature, not a bug, and I would vote to keep it.

That said: email notifications could use some tuning knob. I'd like to turn off email notifications for self-mentions *and* for mentions from bridgy.

**Comment by benwerd** [comment] 2016-02-04 18:08
Self-notifications has actually been a bugbear of mine for a while. I tried to fix it in the last release, but there's still some work to do. It may be that you simply never get notifications from the same hostname as your site.

I turn off all non-comment notifications, which also prevents notifications from Bridgy.

**Comment by mapkyca** [comment] 2019-06-18 12:00
Old, closing

**Closed by mapkyca** 2019-06-18 12:00 UTC
