### ISSUE TITLE
Format posts such that Facebook pulls in the actual image from an image post

### ISSUE THREAD

**Issue by ejheil** [idno/known#2308] opened 2018-12-21 18:12 UTC
**Is your feature request related to a problem? Please describe.**
I noticed when I post an image post to Facebook, it selects my profile pic as the image to use as a thumbnail.  kind of beside the point for an image post.  I know it is possible to suggest the right thing to Facebook with some magic markup or other.

**Describe the solution you'd like**
I would like Facebook to recognize the image as the correct thumbnail for the post, via some magic markup or other

**Describe alternatives you've considered**
Not sure there is one off the top of my head.

**Additional context**
This is something I can and will work on myself when I get time

**Comment by mapkyca** [comment] 2018-12-21 18:15
Duplicate of #2230

**Closed by mapkyca** 2018-12-21 18:15 UTC
