### ISSUE TITLE
Saving a keyed array to config seems to break

### ISSUE THREAD

**Issue by benwerd** [idno/Known#1271] opened 2016-02-19 02:10 UTC
Tested on MongoDB.

Specifically, the hub save action:

```
\Idno\Core\Idno::site()->config->hub_settings = ['registration_token' => bin2hex($token), 'registration_token_expiry' => time()];
```

Is failing out. When I try and query the value of:

```
\Idno\Core\Idno::site()->config()->hub_settings
```

The value returned is the string '[]'.

I haven't had time to check too deeply into this but wanted to recognize it here.

**Comment by mapkyca** [comment] 2016-02-19 09:23
Interesting... I'm on mongo, and I use this often, e.g. to save user config on syndication plugins.

Different mongo version?

**Comment by mapkyca** [comment] 2016-02-19 09:25
As an aside, the given the issues we have with mongo, and the fact we're going to have to rewrite mongo support anyway to use the new library, I'm wondering whether it'd be worth considering whether it's worth dropping mongo support entirely.

Mongo is becoming a bit of an albatross, and I'm starting to think that making inport/export migration really robust would be a better use of resources.

**Comment by mapkyca** [comment] 2016-02-19 09:28
Now dataconciege can support multiple DBs concurrently, one approach would be a CLI which opens two connections - one to mongo, one to the chosen DB, and literally iterates through each collection at the object level - loading from one and saving to the other. That way we'd not have to worry about specific SQL syntax and the whole thing should be DBMS agnostic.

**Comment by mapkyca** [comment] 2016-02-19 11:28
Not that I want to encourage this kind of feature creep, but might it be worth collecting stats on the DB engine used in the next release? If it's only you, me and a couple of highly technical early adopters using Mongo, we can probably kill it without too much grief...

**Comment by kylewm** [comment] 2016-02-20 16:05
First, I do agree that a solid migration path is higher priority than any of this :P

I think the big value in keeping mongo around, even if only a few people use it, is it forces us to keep the storage layer abstract and flexible. Keeps the possibility alive of writing a Couch, DynamoDB, Cloud datastore, etc. backend which could be a huge win in the future.

Now that you've teased apart DataConcierge and Mongo, a slightly less extreme option would be moving it out to a contrib/optional package? (I was thinking about trying to write a Postgres >= 9.4 implementation for my own use, but wouldn't necessarily want it in core)

**Comment by mapkyca** [comment] 2016-02-20 18:27
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1271" class="u-in-reply-to"></a>Agree to keeping things abstract, although I'm  getting pretty pissed off with the ongoing problems caused by Mongo and I'm not looking forward to migrating - including essentially reimplementing GridFS... so a solid migration so I can get back onto MySQL would make me happy....

**Comment by benwerd** [comment] 2016-02-20 18:28
^^^ This.

I'm in favor of discontinuing MongoDB support - but that requires a really good import / export system (which we really need anyway).

**Comment by mapkyca** [comment] 2016-02-20 18:35
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1271#issuecomment-186662849" class="u-in-reply-to"></a>Might have a pop at a script... Shouldn't be too hard to do at the object level...

**Comment by kylewm** [comment] 2016-02-20 18:48
Fair. And if we do scrub Mongo, I would like to eventually get rid of its god awful query syntax :)

**Comment by benwerd** [comment] 2016-02-20 18:49
+1,000,000 :+1:

**Comment by mapkyca** [comment] 2016-08-15 09:19
<a href="https://github.com/idno/Known/issues/1271" class="u-in-reply-to"></a>Just related to this, as I ran into it with ACLS. 

Due to the JSON encapsulation, it is possible to save associated arrays in objects, however they are not *searchable* unless you're on mongo, which allows dot notation.

So, if you want to have a value that is searchable, you'll need to flatten the array in your object's metadata.

**Comment by mapkyca** [comment] 2016-10-28 15:37
Worth retesting since the mongo upgrade

**Comment by mapkyca** [comment] 2017-01-01 18:27
Going to close... seems to work for me.

**Comment by mapkyca** [comment] 2017-04-11 14:52
Reopening as I've verified this on a separate build. Mysql back end.

For me it seems to be related to saving a large compound value, e.g

```$t = ['key' => [1,2,3]];
			\Idno\Core\Idno::site()->config()->test = $t;```

works, but if $t is large, the database entry in config gets corrupted.

**Comment by mapkyca** [comment] 2017-04-11 15:20
Think what I'm actually seeing is #1691

**Closed by mapkyca** 2017-04-11 15:20 UTC
