### ISSUE TITLE
embedded ifram in post

### ISSUE THREAD

**Issue by danito** [idno/Known#1066] opened 2015-09-25 08:50 UTC
I wanted to embed a video from an external site but the iframe is replaced by a &nbsp;. 
I copied the following into the source code of a new post:
````html
<iframe frameborder="0" width="600" height="338" src="http://www.rtl.be/rtltvi/page/rtl-video-en-embed/640.aspx?VideoID=549980">
</iframe><br/>
<a href="http://www.rtl.be/rtltvi/video/549980.aspx" target="_blank">I Like Belgium: Germanophones... oui mais qui sont-ils ?</a>
````
But with no luck.
Is this a feature :-) ?

**Comment by benwerd** [comment] 2015-09-26 02:57
It shouldn't strip iframes. Did you paste it into the source or directly into the WYSIWYG editor?

**Comment by danito** [comment] 2015-09-26 05:48
Into the source editor. I don't think I tried it in the wysiwyg editor.

**Comment by jirkadus** [comment] 2015-09-30 09:34
Could it be related to 0.8.4 update? I updated this morning. I used to use it to insert youtube videos and it worked fine. Now these videos are missing. When I paste the video code, it shows it correctly in the editor, but after publishing, the <iframe> part is gone.

**Comment by buzzworkers** [comment] 2015-10-02 17:10
Having the same problem since my move from stable 0.8.3 to the git hub version Version: 0.8.4
so to reproduce this I simply got the stable version running on another instance, then I moved all the files from the stable version to backup, did a git clone to have all the files from github, then replaced my IdnoPlugins and /upload folder back. 

I also have this bug without touching the plugins/upload folder.

when I returned to the blog, all post with previous Iframe/javascript or manual twitter embed (from a widget or specific search) are gone...simply gone from the post. 

this post https://1-m.cc/2015/evacuation-manu-militari-du-parcmaximilien-bxlrefugees was supposed to show a facebook video along with the text, for some reason anything not pure HTML got stripped out. 
all the javascript after <div class="fb-video"> is gone.

**Comment by buzzworkers** [comment] 2015-10-06 09:29
@benwerd or @mapkyca any idea or quick fix about this? beside going back to 0.8.3 ?

**Comment by benwerd** [comment] 2015-10-06 14:50
We've fixed this in code and will make a new release today. Stand by!

On Tuesday, October 6, 2015, buzzworkers <notifications@github.com> wrote:

> @benwerd <https://github.com/benwerd> or @mapkyca
> <https://github.com/mapkyca> any idea or quick fix about this? beside
> going back to 0.8.3 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1066#issuecomment-145797048>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by buzzworkers** [comment] 2015-10-08 12:06
So great of you !! thanks a lot!!! do you know if previous page with embed code will return as they were OR do we have to edit them all and re add the code ?

**Comment by benwerd** [comment] 2015-10-08 14:29
They should simply return. They were always stored.

On Thursday, October 8, 2015, buzzworkers <notifications@github.com> wrote:

> So great of you !! thanks a lot!!! do you know if previous page with embed
> code will return as they were OR do we have to edit them all and re add the
> code ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/1066#issuecomment-146517907>.
>


-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by buzzworkers** [comment] 2015-10-10 16:13
and they did returned ! thanks a lot for this fix https://1-m.cc/pages/refugeeswelcome it's working !

**Comment by kylewm** [comment] 2015-10-28 03:28
@danito ready to close this issue?

**Closed** 2016-01-29 06:40 UTC
