### ISSUE TITLE
Unusable Admin Panel 

### ISSUE THREAD

**Issue by physcocode** [idno/known#2321] opened 2019-01-15 04:33 UTC
While I was making a known theme I did a mistake which caused my shell to be a little broken which in turn made my admin panel unusable , we should separate the admin panel shell/style from rest of the known shell !

**Comment by mapkyca** [comment] 2019-01-15 08:00
Yep!

This is a duplicate of #1846

**Closed by mapkyca** 2019-01-15 08:00 UTC
