### ISSUE TITLE
Database size

### ISSUE THREAD

**Issue by metaltoast** [idno/Known#972] opened 2015-07-17 12:31 UTC
I'm running a small Known instance with 11 users and about 80 posts as it stands (there's no custom post types but about 50 posts are images). The database is already 8.2MB. This is unsustainable as once over 2 or 3 thousand entities the database will be into the hundreds of MB.

My WordPress installation by comparison with 70 posts (and one user, plus metadata) is 1.0MB.

This appears largely down to Known's use of long ID strings and repetition (posting an entity and then a second entity (with associated metadata) saying "*user* posted..." being created.

Are there any plans to look at this and put the more standard elements of an entity (ie. visibility, date created/ modified, user, slug, title, content etc) into one record and the associated metadata into a second table - similar to WordPress. Along with reducing the size of UIDs it will make Known much more sysadmin friendly.

**Comment by kylewm** [comment] 2015-07-17 14:04
i believe [FriendFeed popularized](https://backchannel.org/blog/friendfeed-schemaless-mysql) this mechanism of storing schema-less data on top of a relational database. it certainly has advantages and disadvantages. with regard to Known my favorite advantage is that plugins can add fields and even new Entity types to the database without modifying the schema! this is a huge win for developers and admins.

i'd be interested to know how big the DB is for an installation with thousands of posts too.

**Comment by benwerd** [comment] 2015-07-17 18:30
Modifying the schema over time is a priority. I also want to revisit the practice of publishing activity stream entities that reference the actual content entity (although we have reasons for doing so).

The rules we've set that dictate our design are:

* Plugin developers should not ever need to touch the schema (eg to create new tables)
* No SQL should ever be written by anyone, except in the data library
* The schema should ideally not change radically over time

Historically, we actually started with a NoSQL back-end before realizing that this was still unsupportable for most people. The existing schema is the result.

**Comment by mapkyca** [comment] 2015-07-18 10:33
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/972" class="u-in-reply-to"></a>Chiming in as well: 

The current schema approach is very easy to build for, which trumps scaling issues for the majority of users, of course everyone's usecase is different. 

That said, the mysql schema could probably do with some optimisation.

Not entirely unrelated, this kind of object based approach maps pretty well onto systems like cassandra, which works pretty well on large high use sites.

**Comment by mapkyca** [comment] 2015-07-27 19:36
Thinking out loud here, would there be any merit for using bson instead of json? Or perhaps just use php's native serialise, which is closer to binary and better stores some values.

**Comment by benwerd** [comment] 2015-07-27 19:40
I'd rather not use BSON - the ability for admins to potentially hand-edit
blobs is useful. There is a larger issue around the way we're doing this to
begin with that is probably the thing to at least think about.

I'm also curious about Postgres's JSON capabilities - for a lot of reasons,
it might be smart to veer in that direction.

On Mon, Jul 27, 2015 at 12:36 PM, Marcus Povey <notifications@github.com>
wrote:

> Thinking out loud here, would there be any merit for using bson instead of
> json? Or perhaps just use php's native serialise, which is closer to binary
> and better stores some values.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/972#issuecomment-125320335>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment] 2015-07-27 19:46
I'd always go for simplicity over efficiency any day, discs and CPU are cheap and not an issue for most. Not really looked at Postgres, though the json stuff looks interesting... Maybe if I get bored.

**Comment by Phyks** [comment] 2015-07-27 19:58
Supporting Postgres would be a real plus I think, especially for
multi-users sites :)

**Comment by benwerd** [comment] 2015-08-18 21:37
Incidentally: in the latest version, clicking to your Site Configuration screen triggers a MySQL optimization that may help with database size.

**Comment by kylewm** [comment] 2016-01-14 17:17
Looking at the metadata table, it looks like it stores the value field as a TEXT, but only indexes the first 255 characters. Would it remove functionality to change TEXT to VARCHAR(255) so that it would only *store* those first 255 characters? I know text can eat up a lot of disk space, and there are bound to be an awful lot metadata rows...

```
CREATE TABLE IF NOT EXISTS `metadata` (
   ...
  `value` text NOT NULL,
   ...
  KEY `value` (`value`(255)),
...
)
```

**Comment by mapkyca** [comment] 2016-01-14 22:04
255 is the max length for indexes on most systems, but quite often we store more than that.

That's ok, it's just slightly less efficient on the retrieval, but we want the ability to *store* still, even if we can't index...

**Comment by benwerd** [comment] 2016-01-14 22:11
Although here, the metadata field is just used for search, not object
reconstitution (for example), so @kylewm makes a good point - the rest of
the stored value is likely redundant.

Unless there's a use case I'm missing out on?

On Thu, Jan 14, 2016 at 2:04 PM, Marcus Povey <notifications@github.com>
wrote:

> 255 is the max length for indexes on most systems, but quite often we
> store more than that.
>
> That's ok, it's just slightly less efficient on the retrieval, but we want
> the ability to *store* still, even if we can't index...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/idno/Known/issues/972#issuecomment-171796514>.
>



-- 
Ben Werdmuller
<http://goog_1933028737>
benwerd.com | werd.io

+1 (312) 488-9373

**Comment by mapkyca** [comment] 2016-01-15 08:52
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/972" class="u-in-reply-to"></a>Hmm... point.

If it's exclusively used for an index, there's no point using a field that's longer than a key length, except of course if we're ever going to use fulltext indexes over it. Although that's only an issue for older installs of MySQL (iirc)

**Comment by kylewm** [comment] 2016-02-04 17:54
datapoint: I have about 8k posts on my site, and my MySQL lib directory is ~500MB (Known's not the only database, but it's the largest by a good margin)

**Comment by physcocode** [comment] 2016-02-04 17:59
This problem arises due to the current data structure of known which i guess is inspired by friends feed am i right @benwerd ?

**Comment by benwerd** [comment] 2016-02-04 18:02
That means a post averages out at around 62kb - _with_ metadata shrinkage. I wonder if the blob is the cause here, and if so, if we'd lose performance by compressing it.

**Comment by kylewm** [comment] 2016-02-04 18:26
OK I have no idea where this information comes from (or why it's so far off from the size-on-disk) but looking at the internal statistics:

```
mysql> SELECT
    ->      table_schema as `Database`,
    ->      table_name AS `Table`,
    ->      round(((data_length + index_length) / 1024 / 1024), 2) `Size in MB`
    -> FROM information_schema.TABLES
    -> ORDER BY (data_length + index_length) DESC;
+--------------------+---------------------------------------+------------+
| Database           | Table                                 | Size in MB |
+--------------------+---------------------------------------+------------+
| known_kylewm_com   | metadata                              |     154.81 |
| known_kylewm_com   | session                               |      52.80 |
| known_kylewm_com   | entities                              |      24.47 |
| known_kylewm_com   | config                                |       0.06 |
| known_kylewm_com   | versions                              |       0.02 |
| known_kylewm_com   | reader                                |       0.00 |
```

Those sizes are pretty manageable, especially considering `entities` is the only bit that would need to be backed up/exported if I was concerned about it.

Interestingly, my metadata table doesn't have a blob column - I changed it to varchar(255)... So it doesn't seem like that's the culprit.

**Comment by kylewm** [comment] 2016-02-04 18:28
Hmm, one wonders why there are 200,000 rows in the session table.

**Comment by mapkyca** [comment] 2016-02-04 22:17
I reckon the session handler isn't cleaning up after itself correctly...

**Comment by kylewm** [comment] 2016-02-05 04:40
Well this is obnoxious. Symfony PdoSessionHandler cleans up expired sessions every so often when PHP does garbage collection. php.ini has a setting `session.gc_probability` that determines how often this gets called. But Ubuntu sets it to 0, and runs the session cleaner thing in a cron job (that has no idea about Known or its database)

**Comment by kylewm** [comment] 2016-02-05 05:56
However if I manually run gc, it removes any session over 24 minutes old and logs me out everywhere... Ok this is a bigger issue than I understood. /me backs away slowly

**Comment by mapkyca** [comment] 2016-02-05 07:39
Yep. Sessions are horrible

The Debian/Ubuntu issues is known - obstensibly to do with security, because they attempt to isolate sessions by keeping them as owned by root. This assumes files of course.

**Comment by mapkyca** [comment] 2016-02-05 07:41
Yep. Sessions are horrible

The Debian/Ubuntu issues is known - obstensibly to do with security, because they attempt to isolate sessions by keeping them as owned by root. This assumes files of course.

**Comment by kylewm** [comment] 2016-02-05 16:17
@mapkyca the Mongo driver [calls `ini_set('session.gc_probability=1')`](https://github.com/idno/Known/blob/master/Idno/Core/DataConcierge.php#L57). I know it's been quite a while since you added that but should we maybe do the same for the SQL impls?

**Comment by mapkyca** [comment] 2016-02-05 16:52
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/972#issuecomment-180425763" class="u-in-reply-to"></a>... probably :)

**Comment by mapkyca** [comment] 2016-10-24 10:43
Closing for now, since this ticket is old.

Changing the DB schema in a major way is something that is unlikely to happen right now, and #1241 will remove session.gc_probability from handleSessions() (which should probably be left for php.ini / system admin to handle.

As an aside, don't forget that DB engines are plugable, so you could easily write an e.g. mysql-high-performance plugin, which stores data in a different format.

**Closed by mapkyca** 2016-10-24 10:43 UTC

**Comment by physcocode** [comment] 2016-10-24 12:27
Just an idea why not give developers to store session into cache like red is or memcache than database itself . 
Symfony session have out of the box support for this

**Comment by mapkyca** [comment] 2016-10-24 12:41
<a href="https://github.com/idno/Known/issues/972" class="u-in-reply-to"></a>I would personally like to see sessions decoupled from the data store, e.g. so you could have a mongo db and a memcache session store or something.
