### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by benwerd** [idno/known#1002] opened 2015-08-06 01:46 UTC
By 1.0, Known needs to be available in multiple languages.

We need to:
- [x] Determine which internationalization format to use (gettext, arrays, other formats all have pluses and minuses)
- [x] Create wrapper function that uses internationalization format
- [x] Convert codebase to use the wrapper function
- [x] Create internationalization files
- [ ] Translate!

I'd love to see Known in French, Spanish, German, Dutch, Russian and Chinese in particular.

Also see: #339 
##

**Comment by akuckartz** [comment] 2015-08-06 04:04
I might want to help with German if Linked Data technologies are used.

**Comment by physcocode** [comment] 2015-08-06 05:07
I am in for hindi !

**Comment by benwerd** [comment] 2015-08-06 06:29
@akuckartz For internationalization?

**Comment by benwerd** [comment] 2015-08-06 06:29
@physcocode Awesome!

**Comment by mapkyca** [comment] 2015-08-06 11:57
<a href="" class="u-in-reply-to"></a><a href="https://github.com/idno/Known/issues/1002" class="u-in-reply-to"></a>Looks like this is a duplicate of #339

**Comment by danito** [comment] 2015-08-06 13:32
I'm in for fr & de, I used to help translate some OS projects with po files (gettext) and some online apps. As you said, every system has its + and - and you can't cover every substition by every language (ask a russian about how they handle their cases) but I think it adds great value for you project if you support internationalization.

**Comment by akuckartz** [comment] 2015-08-06 18:01
@benwerd Yes. One can use LD for internalization.

**Comment by benwerd** [comment] 2015-08-06 18:22
@akuckartz I'd love to learn more about that. Are there any tools that make this easy?

**Comment by benwerd** [comment] 2015-08-06 18:23
@mapkyca Definitely related to #339. I'll bump the title here to translations so they're complementary.

**Comment by jorge-leon** [comment] 2016-07-08 16:11
I can help with German and Spanish.

**Comment by JavierGallego** [comment] 2017-03-02 09:06
I can help with Spanish.

**Comment by mapkyca** [comment] 2017-08-25 13:03
Bumping this a little... Language() appears incomplete... can't see how you switch between languages, detect languages, or populate in a non-horrible way.

Might have a stab at filling this out a little bit more...

**Comment by mapkyca** [comment] 2017-08-30 17:58
<a href="https://github.com/idno/Known/issues/1002" class="u-in-reply-to"></a>Bumping this to flag a recent merge which has a working translation functionality (see test and docs for details).

**Comment by mapkyca** [comment] 2018-10-12 13:57
<a href="https://github.com/idno/Known/issues/1002" class="u-in-reply-to"></a>Bumping again, we now have .pot files for gettext support. PRs totally welcome!

**Comment by mapkyca** [comment] 2019-03-30 18:54
Going to close, based on conversation.

I don't want this to be a blocker for 1.0, and as discussed, the only real requirement is the *ability* to translate, which has been done.

**Closed** 2019-03-30 18:58 UTC
Labels: New feature
